//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public int DepartmentDeptId { get; set; }
        public int EmployeeAddress_StreetNo { get; set; }
        public string EmployeeAddress_StreetName { get; set; }
        public string EmployeeAddress_City { get; set; }
        public string EmployeeAddress_State { get; set; }
    }
}
